version: "3.9"
services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - published: ${DB_PORTS_PUBLISHED}
        target: ${DB_PORTS_TARGET}
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - published: ${BACKEND_PORTS_PUBLISHED}
        target: ${BACKEND_PORTS_TARGET}
    depends_on:
      - db
