version: "3.9"
services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - published: 5555
        target: 5432
