version: "3.9"
services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - published: 5555
        target: 5432
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - published: 8888
        target: 8080
    depends_on:
      - db
