DROP TABLE IF EXISTS task CASCADE;

CREATE TABLE task (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_modified_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content TEXT NOT NULL,
  done BOOLEAN NOT NULL DEFAULT FALSE
);
