spring:
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLED}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    schemas: ${SPRING_FLYWAY_SCHEMAS}
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
custom:
  flyway:
    clean: ${CUSTOM_FLYWAY_CLEAN}
    migrate: ${CUSTOM_FLYWAY_MIGRATE}
